apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tre1
  namespace: default
  labels:
    managed-by: cnpg-admin
spec:
  instances: 3
  storage:
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:16
